### ISSUE TITLE
Automation problem

### ISSUE THREAD

**Issue by Bouni** [Bouni/luxtronik#15]
I can also change these values with the Alpha app.
But these changes are not show in the corresponding input_number.
I have therefor this code:

#if value on Luxtronik changes: set value on slider 
automation:
  - alias: set slider 
    trigger:
      platform: state
      entity_id: sensor.luxtronik.ID_Einst_WK_akt
    action:
      service: input_number.set_value
      data: 
        entity_id: input_number.stooklijn_verschuiving
        value: "{{ states(sensor.luxtronik.ID_Einst_WK_akt) }}"

But I get the error:
ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: Entity ID sensor.luxtronik.ID_Einst_WK_akt is an invalid entity id for dictionary value @ data['entity_id']. Got None. (See ....configuration.yaml, line 21). 

What am I doing wrong??

_Originally posted by @Cees-van-Beek in https://github.com/Bouni/luxtronik/issues/5#issuecomment-771985259_

**Comment by Bouni** [comment]
Please do not hijack other issues.

Can you verify that `sensor.luxtronik.ID_Einst_WK_akt` is a valid entity id using the developer tools of HA?

**Comment by Cees-van-Beek** [comment]
Sorry for the post in the wrong issue.

You are fully right with your question: it should  be "luxtronik.ID_Einst_WK_akt" without "sensor".
The complete and correct yaml-code for this automation is:
`
#if value changes on the luxtronik input_number is adhusted
  - alias: set slider stooklijn verschuiving
    trigger:
      platform: state
      entity_id: luxtronik.ID_Einst_WK_akt
    action:
      service: input_number.set_value
      data: 
        entity_id: input_number.stooklijn_verschuiving
        value: "{{ states('luxtronik.ID_Einst_WK_akt') }}"

#if input_number is changed, the new value is sent to luxtronic
  - alias: set stooklijn verschuiving op luxtronik
    trigger:
    - platform: state
      entity_id: input_number.stooklijn_verschuiving
    action:
      service: luxtronik.write
      data:
        parameter: ID_Einst_WK_akt
      data_template:
        value: '{{ trigger.to_state.state }}'
`
I think the issue can be closed,

**Comment by Bouni** [comment]
Ok, happy that you found the cause of the problem!
