### ISSUE TITLE
Errors during upgrade to latest HACS release 

### ISSUE THREAD

**Issue by RualdOrdelman** [Bouni/luxtronik#18]
I tried to update my Luxtronic HACS integration from 0.1.12 to 0.1.15. My HassIO won't boot after that upgrade. 
First I saw the following error in the log:

`
Fatal error while loading config: inconsistent use of tabs and spaces in indentation (__init__.py, line 136)
Failed config
  General Errors: 
    - inconsistent use of tabs and spaces in indentation (__init__.py, line 136)
`

I corrected the tabs on line 136 and tried to restart. Then I get the following error:
`Fatal error while loading config: name 'CONF_LOCK_TIMEOUT' is not defined
Failed config
  General Errors: 
    - name 'CONF_LOCK_TIMEOUT' is not defined`

I tried to go back to 0.1.13 but then I got the errors. So I deinstalled the component en installed version 0.1.12 and now my integration working again.

**Comment by Bouni** [comment]
Thanks for the hint, i'll take a look at it and push out a new release in the next few minutes!
