### ISSUE TITLE
Luxtronik 2.0 Firmware 1.8, Java Applet Webinterface

### ISSUE THREAD

**Issue by tunguskar** [Bouni/luxtronik#24]
Hi there,
My Luxtronik 2.0 has the firmware 1.8. This works with a Java Applet (port 8889) for the web Interface. Is this supported? Because I have problems at the moment to connect to it. With FHEM there is no Problem to connect to. 

Does anybody know about this issue?

```text
Logger: homeassistant.setup
Source: custom_components/luxtronik/__init__.py:99 
Integration: luxtronik 
First occurred: 9:00:40 (1 occurrences) 
Last logged: 9:00:40
Error during setup of component luxtronik
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 255, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/luxtronik/__init__.py", line 72, in setup
    luxtronik = LuxtronikDevice(host, port, safe, lock_timeout)
  File "/config/custom_components/luxtronik/__init__.py", line 99, in __init__
    self._luxtronik = Lux(host, port, safe)
  File "/usr/local/lib/python3.9/site-packages/luxtronik/__init__.py", line 25, in __init__
    self.read()
  File "/usr/local/lib/python3.9/site-packages/luxtronik/__init__.py", line 38, in read
    self._connect()
  File "/usr/local/lib/python3.9/site-packages/luxtronik/__init__.py", line 29, in _connect
    self._socket.connect((self._host, self._port))
OSError: [Errno 101] Network unreachable

```

**Comment by Bouni** [comment]
Can you try to verify if ip and port are correct?
For example using `telnet 192.168.1.100 8889` (change the IP to that of you heatpump)

Someone in the past had the same problem and it was an incorrect ip / port.

Also older versions used port 8888, maybe thats the case for you.

**Comment by tunguskar** [comment]
This works. I get an online status via telnet and the port 8889

**Comment by Bouni** [comment]
How do you run HA? HAOS? Docker Image?

**Comment by tunguskar** [comment]
HAOS, Version
core-2021.9.7
--

**Comment by Bouni** [comment]
Can you verify that you can ping the heatpump from within the HAOS container?
I run HA as docker container and need to run this specific container with `network_mode: "host"` in order to be able to connect to the heatpump.

**Comment by tunguskar** [comment]
do you know how to do a ping on haos console. Seems there is nothing installed

**Comment by Bouni** [comment]
I've never used HAOS before but I guess thats your way to get shell access to the OS:

https://developers.home-assistant.io/docs/operating-system/debugging/#ssh-access-to-the-host

**Comment by Bouni** [comment]
from there you should be able to use `ip a` to verify that you have an IP withn the same range as your heatpump and maybe there's ping installed

**Comment by tunguskar** [comment]
I got the ping to run. And yes the heat pump reply's: `ping 192.168.1.xx`

64 bytes from 192.168.1.xx: seq=0 ttl=63 time=1.906 ms

**Comment by Bouni** [comment]
Ok thats from the OS, to my undertanding HA runs as a container within the OS.
I don't know how to get acces to that, but as a workaround you cound use the ping itegration to see if you're able to ping from HA:

**Comment by tunguskar** [comment]
Hi Bouni, I tried the ping and yes you are right, No connection possible.

**Comment by tunguskar** [comment]
I did some settings in proxmox hardware adapter for the network. There was a switch to turn off dedicated firewall. No it works :)

**Comment by tunguskar** [comment]
Thank you Bouni for your support
