### ISSUE TITLE
Alpha Innotec MSW2-6S 

### ISSUE THREAD

**Issue by elgrande-nl** [Bouni/luxtronik#29]
Hi there,

I can't connect to My Alpha Innotec heatpump. Is this version supported?

It seems that port 8889 is closed on the controler only (80,22 and 502) are opend.

the webinterface on port 80 is giving me a java webinterface.

Anny thoughts?

**Comment by Bouni** [comment]
I know that older versions used the port 8888 instead of 8889!

You could try to use nmap to verify what ports are open:
```
nmap -p 22,80,8888,8889 192.168.178.100
Starting Nmap 7.92 ( https://nmap.org ) at 2021-12-22 09:11 CET
Nmap scan report for wp.home (192.168.178.100)
Host is up (0.00045s latency).

PORT     STATE  SERVICE
22/tcp   open   ssh
80/tcp   open   http
8888/tcp closed sun-answerbook
8889/tcp open   ddi-tcp-2

Nmap done: 1 IP address (1 host up) scanned in 0.11 seconds
```

You see in my case ports 22, 80 and 8889 are open but not 8888. In your case it could be the other way round.

**Comment by elgrande-nl** [comment]
It seems that port 8889 is in state open.
After a couple of restarts suddenly it works.
