### ISSUE TITLE
Wrong device_class for temperature sensors

### ISSUE THREAD

**Issue by mtdcr** [Bouni/luxtronik#3]
I just noticed that all my luxtronik temperature sensors have the state attribute `device_class: pressure`.

Before using your integration, I had an integration written by myself, which had the same name and same entity IDs. So there is a chance that it might be a leftover from back then (many months ago).

Can you confirm the device_class in your setup?

I currently don't have any customizations in Home Assistant.

**Comment by Bouni** [comment]
That's inded a bug, I'll fix it asap!
