### ISSUE TITLE
Luxtronik integration not found anymore

### ISSUE THREAD

**Issue by remyderuysscher** [Bouni/luxtronik#31]
On HA 2021.12.9 

After upgrading to 0.1.22 the configuration check of HA gives this error:

`Integration error: luxtronik - Integration 'luxtronik' not found.
Platform error binary_sensor.luxtronik - Integration 'luxtronik' not found.
Platform error sensor.luxtronik - Integration 'luxtronik' not found.`

Reinstalling and downgrading doesn't work.

**Comment by Bouni** [comment]
Ok, let me take a look into it

**Comment by remyderuysscher** [comment]
Downgrading to HA core 2021.12.8 doesn't work either.

**Comment by Bouni** [comment]
Thats strange, I run the exact same combination `Home Assistant 2021.12.9` and `0.1.22` and had an network error in the logs.
So I thought thats what you see but after a restart of HA it al started up fine.

How do you run HA? (docker container, HASSIO ...)

**Comment by remyderuysscher** [comment]
I run HASSIO on an Odroid N2.

**Comment by remyderuysscher** [comment]
Strange, I removed the custom component directory reinstalled and restarted HA now it's working again on HA 2021.12.8.

**Comment by Bouni** [comment]
Would you mind upgrading to 2021.12.9 to verify that it works for you as well?

**Comment by remyderuysscher** [comment]
I rather not, but I'll do it anyway. And it works! Thanks for the effort, must be a glitch somewhere.

**Comment by Bouni** [comment]
No worries, always good to hear that nothing is seriously broken 😉
