### ISSUE TITLE
Not in list

### ISSUE THREAD

**Issue by WolfsWelpe** [Bouni/luxtronik#39]
Heyho I just noticed some errors popping up in my logs:

> Logger: Luxtronik.Visibilities
> Source: /usr/local/lib/python3.9/site-packages/luxtronik/visibilities.py:377
> First occurred: 14. April 2022, 17:53:28 (2069 occurrences)
> Last logged: 20:54:38
> 
> Visibility '355' not in list of visibilities

> Logger: Luxtronik.Calculations
> Source: /usr/local/lib/python3.9/site-packages/luxtronik/calculations.py:309
> First occurred: 14. April 2022, 17:53:28 (6207 occurrences)
> Last logged: 20:54:38
>
> Calculation '260' not in list of calculationss
> Calculation '261' not in list of calculationss
> Calculation '262' not in list of calculationss

> Logger: Luxtronik.Parameters
> Source: /usr/local/lib/python3.9/site-packages/luxtronik/parameters.py:1165
> First occurred: 14. April 2022, 17:53:28 (2069 occurrences)
> Last logged: 20:54:38
> 
> Parameter '1126' not in list of parameters

At the moment this is my config:

> - platform: luxtronik
  scan_interval: 30
  sensors:
    - id: ID_WEB_Temperatur_TA
      friendly_name: Aussentemperatur_raw
      group: calculations
    - id: ID_Soll_BWS_akt
      friendly_name: Haus_Warmwasser_Soll
      group: parameters
    - id: ID_WEB_Temperatur_TVL
      friendly_name: Haus_Vorlauf
      group: calculations
    - id: ID_WEB_Temperatur_TRL
      friendly_name: Haus_Ruecklauf
      group: calculations
    - id: ID_WEB_Temperatur_TBW
      friendly_name: Haus_Warmwasser_Ist
      group: calculations
    - id: ID_Ba_Hz_akt
      friendly_name: Haus_Heating_Circuit
      group: parameters
    - id: ID_Ba_Bw_akt
      friendly_name: Haus_Warmwasser_Circuit
      group: parameters
    - id: ID_WEB_WP_BZ_akt
      friendly_name: Haus_Current_State
      group: calculations

**Comment by WolfsWelpe** [comment]
![image](https://user-images.githubusercontent.com/17033125/164824617-a4edb015-0b61-46ed-9c52-b587f4b01c7c.png)

**Comment by Bouni** [comment]
This simply means that your version of the firmware reports more data back than this plugin currently is aware of.
I think wee should change the way of how the plugin handles unknown parameters to prevent filling up the logs ...

**Comment by Ornias1993** [comment]
same problem on an alpha innotec. 
A shame really :(

**Comment by Bouni** [comment]
The latest release should prevent the filling of the logs as well as automatically add unknown Calculations/Parameters/Visibilities as `Unknown_[Calculation|Parameter|Visibility]_<number>`.

I cannot test this as I have no additional unknown parameters, so please let me know if this works for you guys!

**Comment by WolfsWelpe** [comment]
> I cannot test this as I have no additional unknown parameters, so please let me know if this works for you guys!

Sorry for the late respone! It is working, at least I'm not getting any log entries anymore about unkown parameters etc.

**Comment by Bouni** [comment]
Nice, thanks for the feedback!
