### ISSUE TITLE
[Errno 111] Connection refused

### ISSUE THREAD

**Issue by antsmartti** [Bouni/luxtronik#44]
I'm running latest HAOS in Proxmox VM. A new Alpha Innotec heat pump was installed earlier this week, but looks like can't setup the integration in HA. Installed Luxtronik via HACS. 

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/luxtronik/__init__.py", line 74, in setup
    luxtronik = LuxtronikDevice(host, port, safe, lock_timeout)
  File "/config/custom_components/luxtronik/__init__.py", line 101, in __init__
    self._luxtronik = Lux(host, port, safe)
  File "/usr/local/lib/python3.10/site-packages/luxtronik/__init__.py", line 25, in __init__
    self.read()
  File "/usr/local/lib/python3.10/site-packages/luxtronik/__init__.py", line 40, in read
    self._connect()
  File "/usr/local/lib/python3.10/site-packages/luxtronik/__init__.py", line 29, in _connect
    self._socket.connect((self._host, self._port))
ConnectionRefusedError: [Errno 111] Connection refused
```
- I can ping the IP and it's visible in my router
- The IP doesn't show up with `netstat -a`
- `telnet 192.168.1.2xx 8889` gives `telnet: Unable to connect to remote host: Connection refused`, same with port 8888
- Tried `nmap -p 22,80,8888,8889 192.168.1.2xx`, it says host is up but every port is in closed state
- I added the pump to myupway.com, I can see everything in real-time. Was that a mistake?

This is my current entry in configuration.yaml:
```
#alpha innotec
luxtronik:
  host: 192.168.1.2xx
  port: 8889

sensor:
  - platform: luxtronik
    sensors:
      - group: calculations
        id: ID_WEB_Temperatur_TVL
```

Both HA and pump needed updates, but same situation after updating and rebooting. Is there something I should do in the settings of the pump beforehand? Could the device be locked by the manufacturer somehow?

**Comment by Bouni** [comment]
What model of heatpump do you have?

I've never heard of myupway.com, so you might got a new model that has some kind of luxtronik 3 or so ...

**Comment by antsmartti** [comment]
Hi! The controller seems to be NP-CS40? https://www.alpha-innotec.ch/alpha-innotec/produkte/internet-anbindung/np-cs-40-endkunde.html
The pump itself is HT 12 split. During installation I peeked behind the cover and most of the chips had Nibe logos on them.

**Comment by Bouni** [comment]
That's what I just wanted to write you. I guess the go to a cloud only model with their new Heatpumps.
Very unfortunate in my eyes 🫤
