### ISSUE TITLE
Error in write parameters

### ISSUE THREAD

**Issue by Bouni** [Bouni/luxtronik#6]
Bouni,  i have problem right now to write something to any ID. Even in HA doesn't show up the instruction in developer options: 

![image](https://user-images.githubusercontent.com/65340460/88293099-d5dad480-ccfa-11ea-80f4-d5597cbd4e3e.png)

And come this error:

![image](https://user-images.githubusercontent.com/65340460/88293165-eb4ffe80-ccfa-11ea-88c3-7c9e3f646631.png)

_Originally posted by @MrLukson in https://github.com/Bouni/luxtronik/issues/5#issuecomment-663013668_

**Comment by Bouni** [comment]
💩 I think i introduced a bug with my recent changes, will fix it asap!

**Comment by Bouni** [comment]
OK, fixed! New version available via HACS

**Comment by MrLukson** [comment]
It's working. Thank you very much for such fast help !
