### ISSUE TITLE
Luxtronik Invallid config

### ISSUE THREAD

**Issue by BobPuts** [Bouni/luxtronik#7]
Hi there,

Since 0.113 I guess Luxtronik isn't working anymore. It seems that Home Assistant has removed the intergration. Do you now more about this or does it need to work without the intergration?

I have followed the guide you provided and it worked well till the update to 0.113.

Invalid config
The following integrations and platforms could not be set up:

luxtronik
luxtronik.binary_sensor
luxtronik.sensor
Please check your config.

**Comment by Bouni** [comment]
I run 0.113 myself and everything works fine!?
Did you install it using HACS?

**Comment by BobPuts** [comment]
I did install it using HACS. I will try removing the plugin from HACS and install it again. I also attached the yaml as a txt file
[luxtronik.txt](https://github.com/Bouni/luxtronik/files/5082413/luxtronik.txt)

**Comment by Bouni** [comment]
Strange! I just checkt my version, I run 0.113.3 and the integration works fine.
My config also looks very similar to yours.

**Comment by BobPuts** [comment]
I have even upgraded it to the latest release: 0.114.1. Still doesn't work. Removed the HACS plugin and reinstalled it. Will try to remove it and reboot the system to check if this work but I'm afraid it wont.

**Comment by BobPuts** [comment]
I also noticed that the luxtronik dissapeared from the intergration page. https://www.home-assistant.io/integrations/luxtronik Maybe this has something to do with each other?

**Comment by Bouni** [comment]
I think it was never there, as its no official integration! Thats why you install it using HACS.

**Comment by Bouni** [comment]
Do you see anything in the logs that could help find out whats wrong!?

**Comment by BobPuts** [comment]
If I check the logs I see the following:
2020-08-17 17:27:54 ERROR (MainThread) [homeassistant.setup] Error during setup of component luxtronik
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 191, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/luxtronik/__init__.py", line 64, in setup
    luxtronik = LuxtronikDevice(host, port, safe)
  File "/config/custom_components/luxtronik/__init__.py", line 89, in __init__
    self._luxtronik = Lux(host, port, safe)
  File "/usr/local/lib/python3.8/site-packages/luxtronik/__init__.py", line 25, in __init__
    self.read()
  File "/usr/local/lib/python3.8/site-packages/luxtronik/__init__.py", line 38, in read
    self._connect()
  File "/usr/local/lib/python3.8/site-packages/luxtronik/__init__.py", line 29, in _connect
    self._socket.connect((self._host, self._port))

**Comment by Bouni** [comment]
Maybe your HA setup cannot connect to the heatpump for some reason. 
To be honest, I've never tested for this scenario :grimacing: 

Can you verify that the pump is reachable?

**Comment by Bouni** [comment]
I was able to reproduce the issue on my setup!

```
home-assistant   |     self._connect()
home-assistant   |   File "/usr/local/lib/python3.8/site-packages/luxtronik/__init__.py", line 29, in _connect
home-assistant   |     self._socket.connect((self._host, self._port))
home-assistant   | ConnectionRefusedError: [Errno 111] Connection refused
```
If I set a wrong IP in my config the error seems to be the same!

**Comment by BobPuts** [comment]
Yes I see. Have changed it and it is working again thanks!
