### ISSUE TITLE
Set up a heat pump (Alpha Innotec)

### ISSUE THREAD

**Issue by SchBenedikt** [Bouni/luxtronik#77]
Let's say I have an Alpha Innotec heat pump. There are then various configuration options such as: B. IP address or port for the config file. What do you have to write in there so that everything is configured correctly?
What exactly do you mean by port? Is it always 8889 or how can I find out?
Unfortunately there is no suitable description for this...

Best regards and many thanks in advance,
schBenedikt

**Comment by BenPru** [comment]
> What do you have to write in there so that everything is configured correctly?

See [Configuration in readme](https://github.com/Bouni/luxtronik#configuration)

> What exactly do you mean by port?

The unix socket network port of the heatpump.

>  Is it always 8889 or how can I find out?

8889 for current firmware versions and 8888 for legacy firmwares.
You can use this script to lookup your network for the heatpump and its ports:
https://gist.github.com/BenPru/ec463ea835fb705b070939c793196f2e

**Comment by SchBenedikt** [comment]
Thanks!
