### ISSUE TITLE
Luxtronik no longer works after updating Home Assistant.

### ISSUE THREAD

**Issue by Bello2023** [Bouni/luxtronik#79]
After updating HomeAssist from version 2023.12.4 to 2024.1.0
Luxtronik2 no longer starts, and I receive the following error message:

Home Assistant Core
Setup failed for custom integration 'luxtronik2': Unable to import component: Exception importing custom_components.luxtronik2
19:33:49 – (ERROR) setup.py
Unexpected exception importing component custom_components.luxtronik2
19:33:49 – (ERROR) loader.py

What is going wrong?

**Comment by matbody** [comment]
Same in my installation. ?

**Comment by Bouni** [comment]
I'll look into it tomorrow. Don't have time today, sorry 😐

**Comment by Bello2023** [comment]
https://github.com/BenPru/luxtronik/pull/227 fix this issue. I manually applied the code lines and integration is working now.
