### ISSUE TITLE
force Alpha Innotec to use new values

### ISSUE THREAD

**Issue by gris3o** [Bouni/luxtronik#82]
First of all, Thank you so much for the integration it works perfect for reading my alpha innotec,

I'm also able to send new setting to the unit. But the unit then decides on its own when to execute them.

The setup i'm trying to accomplish is this:
When energy prices are negative, I set the hot water temperature 4 degrees hotter. 
This works but the alpha innotec does not start to heat the water to the new setpoint, it will at a random (at least that is how it feels) time use the new temperature.

is there any way to force the alpha innotec unit to start heating the water when i want to?

Thank you,
Roel

**Comment by Bouni** [comment]
I think someone had a trick he mentioned in another issue where he used TDI (thermal disinfection) to start the hot water cycle immediately (or something like that, I don't remember)

**Comment by gris3o** [comment]
Thanks for the quick replay,
You are right in:
Question: Thermal Disinfection control #42
https://github.com/Bouni/luxtronik/issues/42

there is a solution for this problem.

you can close this issue
